import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { TripMapSurface } from "@/features/maps/components/TripMapSurface";
import type { LocalActivity } from "@/features/trips/hooks/useLocalTripWorkspace";

type LocationChoice={id:string;name:string;displayName:string;latitude:number;longitude:number};
const QUICK:LocationChoice[]=[
{id:"mcia",name:"Mactan–Cebu International Airport",displayName:"(MCIA) Terminal 1, Lapu-Lapu City Cebu, Philippines",latitude:10.3075,longitude:123.9794},
{id:"mcia2",name:"Mactan–Cebu International Airport Terminal 2",displayName:"Terminal 2, Lapu-Lapu City, Cebu, Philippines",latitude:10.3090,longitude:123.9799},
{id:"mcia1",name:"Mactan–Cebu International Airport Terminal 1",displayName:"Terminal 1 Road, Lapu-Lapu City, Cebu, Philippines",latitude:10.3072,longitude:123.9792},
{id:"newtown",name:"Mactan Newtown",displayName:"The Mactan Newtown, Lapu-Lapu City, Cebu, Philippines",latitude:10.3070,longitude:124.0135},
{id:"shrine",name:"Mactan Shrine",displayName:"Punta Engaño Rd, Lapu-Lapu City, Cebu, Philippines",latitude:10.3100,longitude:124.0156},
];

export function PremiumItineraryEditor({value,day,onClose,onSave,onDelete}:{
  value:LocalActivity|null|"new";day:number;onClose():void;onSave(input:Omit<LocalActivity,"id"|"dayNumber">):void;onDelete?():void;
}){
  const current=value&&value!=="new"?value:null;
  const [query,setQuery]=useState(current?.locationName??current?.title??"Mactan Cebu International Airport");
  const [results,setResults]=useState<LocationChoice[]>(QUICK);
  const [loading,setLoading]=useState(false);
  const [choice,setChoice]=useState<LocationChoice|null>(()=>current?.latitude!=null&&current?.longitude!=null?{id:current.id,name:current.locationName,displayName:current.detail||current.locationName,latitude:current.latitude,longitude:current.longitude}:QUICK[0]);
  const [cost,setCost]=useState(current?.estimatedCost?String(current.estimatedCost):"");
  const [notes,setNotes]=useState(current?.detail??"");
  const initial=toWheel(current?.startTime??"08:00");
  const [hour,setHour]=useState(initial.hour);const [minute,setMinute]=useState(initial.minute);const [meridiem,setMeridiem]=useState(initial.meridiem);
  const req=useRef(0);

  useEffect(()=>{
    const text=query.trim();if(text.length<2){setResults(QUICK);return;}
    const local=QUICK.filter(item=>`${item.name} ${item.displayName}`.toLowerCase().includes(text.toLowerCase()));
    const id=++req.current;const timer=setTimeout(async()=>{setLoading(true);try{const response=await fetch(`https://photon.komoot.io/api/?q=${encodeURIComponent(text)}&limit=7`);if(!response.ok)throw new Error("search");const json=await response.json() as {features?:Array<{geometry?:{coordinates?:[number,number]};properties?:Record<string,string|number|null|undefined>}>};if(id!==req.current)return;const remote=(json.features??[]).flatMap((feature,index)=>{const coords=feature.geometry?.coordinates;if(!coords||!Number.isFinite(coords[0])||!Number.isFinite(coords[1]))return[];const p=feature.properties??{};const name=String(p.name??p.city??p.street??"Location");const parts=[p.name,p.street,p.city,p.state,p.country].filter((part,i,arr)=>part&&arr.indexOf(part)===i).map(String);return[{id:String(p.osm_id??`${coords[1]}-${coords[0]}-${index}`),name,displayName:parts.join(", ")||name,latitude:coords[1],longitude:coords[0]} satisfies LocationChoice];});const seen=new Set<string>();setResults([...local,...remote].filter(item=>{const key=`${item.latitude.toFixed(5)}:${item.longitude.toFixed(5)}`;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,6));}catch{if(id===req.current)setResults(local.length?local:QUICK);}finally{if(id===req.current)setLoading(false);}},260);return()=>clearTimeout(timer);
  },[query]);

  const mapActivities=useMemo(()=>choice?[{id:"preview",title:choice.name,category:"other",locationName:choice.displayName,latitude:choice.latitude,longitude:choice.longitude}]:[],[choice]);
  function choose(item:LocationChoice){setChoice(item);setQuery(item.name);if(!notes||notes===current?.detail)setNotes(item.displayName);}
  function save(){if(!choice)return;onSave({title:choice.name,locationName:choice.name,detail:notes.trim()||choice.displayName,latitude:choice.latitude,longitude:choice.longitude,category:current?.category??"other",startTime:fromWheel(hour,minute,meridiem),estimatedCost:Number(cost)||0});}

  return <Modal visible transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.modal}>
    <View style={s.head}><Text style={s.title}>{current?"Edit Itinerary Item":`Add Itinerary Item · Day ${day}`}</Text><Pressable onPress={onClose} style={s.close}><Ionicons name="close" size={23} color="#56637B"/></Pressable></View>
    <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}>
      <View style={s.search}><Ionicons name="search" size={22} color="#6E7D98"/><TextInput value={query} onChangeText={setQuery} placeholder="Search a place" placeholderTextColor="#93A0B4" autoCorrect={false} style={s.searchInput}/>{loading?<ActivityIndicator size="small" color="#5E73F3"/>:query?<Pressable onPress={()=>setQuery("")}><Ionicons name="close-circle" size={20} color="#A5ADBA"/></Pressable>:null}</View>
      <View style={s.results}>{results.map((item,index)=>{const selected=choice?.id===item.id;return <Pressable key={item.id} onPress={()=>choose(item)} style={[s.result,index===results.length-1&&s.resultLast]}><LinearGradient colors={selected?["#4F7CF7","#BD6EED"]:index===3?["#FFC66F","#FF9D5E"]:index===4?["#FB6F86","#F48A9A"]:["#3AAEF7","#9B69F4"]} style={s.resultIcon}><Ionicons name={index===0?"airplane":"location"} size={19} color="#FFF"/></LinearGradient><View style={s.resultCopy}><Text numberOfLines={1} style={s.resultName}>{item.name}</Text><Text numberOfLines={1} style={s.resultAddress}>{item.displayName}</Text></View>{selected?<View style={s.check}><Ionicons name="checkmark" size={17} color="#FFF"/></View>:<Ionicons name="chevron-forward" size={20} color="#AAB4C4"/>}</Pressable>})}<Pressable onPress={()=>setQuery("")} style={s.searchMap}><Ionicons name="map-outline" size={20} color="#77849B"/><Text style={s.searchMapText}>Search on map</Text></Pressable></View>
      {choice?<View style={s.mapWrap}><TripMapSurface activities={mapActivities} selectedActivityId="preview" height={220}/><View style={s.mapLabel}><Text style={s.mapLabelText}>{choice.name}</Text></View><View style={s.mapNavigate}><Ionicons name="navigate" size={22} color="#25324C"/></View></View>:null}
      {choice?<View style={s.detected}><View style={s.detectedIcon}><Ionicons name="checkmark" size={16} color="#FFF"/></View><Text style={s.detectedText}>Auto-detected location · {choice.latitude.toFixed(4)}, {choice.longitude.toFixed(4)}</Text><Pressable><Text style={s.change}>Change</Text></Pressable></View>:null}

      <View style={s.scheduleHead}><View style={s.scheduleTitleRow}><Ionicons name="time-outline" size={20} color="#34435F"/><Text style={s.scheduleTitle}>Schedule</Text></View><View style={s.timezone}><Text style={s.timezoneText}>GMT+8</Text></View></View>
      <View style={s.wheels}><TimeWheel values={Array.from({length:12},(_,i)=>String(i+1).padStart(2,"0"))} value={hour} onChange={setHour}/><TimeWheel values={Array.from({length:60},(_,i)=>String(i).padStart(2,"0"))} value={minute} onChange={setMinute}/><TimeWheel values={["AM","PM"]} value={meridiem} onChange={(value)=>setMeridiem(value as "AM"|"PM")}/></View>

      <View style={s.fieldLabelRow}><Ionicons name="cash-outline" size={20} color="#40506B"/><Text style={s.fieldLabel}>Estimated cost (PHP)</Text></View><TextInput value={cost} onChangeText={text=>setCost(text.replace(/[^0-9.]/g,""))} keyboardType="decimal-pad" placeholder="0.00" placeholderTextColor="#8F9AAF" style={s.input}/>
      <View style={s.fieldLabelRow}><Ionicons name="document-text-outline" size={20} color="#40506B"/><Text style={s.fieldLabel}>Notes (optional)</Text></View><View style={s.notesWrap}><TextInput value={notes} onChangeText={text=>setNotes(text.slice(0,200))} multiline placeholder="Add notes about this stop…" placeholderTextColor="#8F9AAF" style={s.notes}/><Text style={s.count}>{notes.length}/200</Text></View>

      <View style={s.actions}>{onDelete?<Pressable onPress={onDelete} style={s.delete}><Ionicons name="trash-outline" size={20} color="#EF4260"/><Text style={s.deleteText}>Delete</Text></Pressable>:null}<Pressable onPress={onClose} style={s.cancel}><Text style={s.cancelText}>Cancel</Text></Pressable><Pressable onPress={save} style={s.savePress}><LinearGradient colors={["#76B7F8","#A2A7F3","#EF8AB8"]} start={{x:0,y:.5}} end={{x:1,y:.5}} style={s.save}><Text style={s.saveText}>{current?"Save changes":"Add activity"}</Text></LinearGradient></Pressable></View>
    </ScrollView>
  </View></View></Modal>;
}

function TimeWheel({values,value,onChange}:{values:string[];value:string;onChange(value:string):void}){const index=Math.max(0,values.indexOf(value));const before=values[(index-1+values.length)%values.length];const after=values[(index+1)%values.length];return <View style={s.wheel}><Pressable onPress={()=>onChange(before)}><Text style={s.wheelFade}>{before}</Text></Pressable><View style={s.wheelSelected}><Text style={s.wheelSelectedText}>{value}</Text></View><Pressable onPress={()=>onChange(after)}><Text style={s.wheelFade}>{after}</Text></Pressable></View>;}
function toWheel(time:string){const [hRaw="8",mRaw="00"]=time.split(":");let h=Number(hRaw);const meridiem: "AM" | "PM" = h >= 12 ? "PM" : "AM";h=h%12||12;return{hour:String(h).padStart(2,"0"),minute:String(Number(mRaw)||0).padStart(2,"0"),meridiem};}
function fromWheel(hour:string,minute:string,meridiem:"AM"|"PM"){let h=Number(hour)%12;if(meridiem==="PM")h+=12;return`${String(h).padStart(2,"0")}:${String(Number(minute)).padStart(2,"0")}`;}

const s=StyleSheet.create({
backdrop:{flex:1,alignItems:"center",justifyContent:"center",padding:18,backgroundColor:"rgba(19,29,51,.34)"},modal:{width:"100%",maxWidth:640,maxHeight:"94%",borderRadius:31,backgroundColor:"#FFF",borderWidth:1,borderColor:"rgba(255,255,255,.72)",boxShadow:"0 30px 70px rgba(27,38,63,.20)"},head:{height:76,paddingHorizontal:24,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{color:"#101A35",fontSize:20,fontWeight:"900"},close:{width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center",backgroundColor:"#F7F9FC",borderWidth:1,borderColor:"#E4E8EF"},scroll:{paddingHorizontal:22,paddingBottom:22},
search:{minHeight:58,paddingHorizontal:15,borderRadius:18,flexDirection:"row",alignItems:"center",gap:10,backgroundColor:"#FFF",borderWidth:1,borderColor:"#DFE4EC"},searchInput:{flex:1,minHeight:54,color:"#17213B",fontSize:13,fontWeight:"700"},results:{marginTop:12,overflow:"hidden",borderRadius:19,borderWidth:1,borderColor:"#E3E7EE",backgroundColor:"#FFF"},result:{minHeight:67,paddingHorizontal:14,flexDirection:"row",alignItems:"center",gap:11,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:"#E8ECF2"},resultLast:{},resultIcon:{width:42,height:42,borderRadius:12,alignItems:"center",justifyContent:"center"},resultCopy:{flex:1,minWidth:0},resultName:{color:"#17213B",fontSize:12,fontWeight:"900"},resultAddress:{marginTop:4,color:"#7A879B",fontSize:9,fontWeight:"600"},check:{width:28,height:28,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:"#2E6DF6"},searchMap:{minHeight:54,paddingHorizontal:15,flexDirection:"row",alignItems:"center",gap:10},searchMapText:{color:"#5A6982",fontSize:11,fontWeight:"700"},
mapWrap:{marginTop:14,height:220,overflow:"hidden",borderRadius:18,position:"relative"},mapLabel:{position:"absolute",left:0,right:0,bottom:18,alignItems:"center"},mapLabelText:{paddingHorizontal:10,paddingVertical:4,borderRadius:10,overflow:"hidden",backgroundColor:"rgba(255,255,255,.84)",color:"#2447A1",fontSize:11,fontWeight:"900"},mapNavigate:{position:"absolute",right:15,bottom:15,width:52,height:52,borderRadius:26,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(255,255,255,.96)",boxShadow:"0 8px 19px rgba(38,56,88,.16)"},detected:{marginTop:12,minHeight:48,paddingHorizontal:12,borderRadius:14,flexDirection:"row",alignItems:"center",gap:9,backgroundColor:"#F4FAF7",borderWidth:1,borderColor:"#E2F0E8"},detectedIcon:{width:20,height:20,borderRadius:10,alignItems:"center",justifyContent:"center",backgroundColor:"#4DB58B"},detectedText:{flex:1,color:"#4C9A78",fontSize:10,fontWeight:"800"},change:{color:"#674BFF",fontSize:10,fontWeight:"900"},
scheduleHead:{marginTop:14,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},scheduleTitleRow:{flexDirection:"row",alignItems:"center",gap:8},scheduleTitle:{color:"#34435F",fontSize:12,fontWeight:"900"},timezone:{paddingHorizontal:10,paddingVertical:6,borderRadius:14,backgroundColor:"#F2F6FB"},timezoneText:{color:"#5C6E8A",fontSize:9,fontWeight:"800"},wheels:{marginTop:9,height:118,flexDirection:"row",justifyContent:"center",gap:2},wheel:{width:120,alignItems:"center",justifyContent:"center"},wheelFade:{height:32,textAlign:"center",color:"#B7BBC4",fontSize:15,fontWeight:"600"},wheelSelected:{width:"100%",height:36,borderRadius:7,alignItems:"center",justifyContent:"center",backgroundColor:"#F1F2F6"},wheelSelectedText:{color:"#14171E",fontSize:17,fontWeight:"800"},
fieldLabelRow:{marginTop:15,marginBottom:7,flexDirection:"row",alignItems:"center",gap:8},fieldLabel:{color:"#40506B",fontSize:11,fontWeight:"900"},input:{height:53,paddingHorizontal:14,borderRadius:16,color:"#17213B",fontSize:12,fontWeight:"700",borderWidth:1,borderColor:"#E2E6EE"},notesWrap:{minHeight:88,borderRadius:16,borderWidth:1,borderColor:"#E2E6EE",padding:13,position:"relative"},notes:{minHeight:58,color:"#17213B",fontSize:11,textAlignVertical:"top"},count:{position:"absolute",right:12,bottom:9,color:"#8E9AAF",fontSize:8,fontWeight:"700"},actions:{marginTop:18,flexDirection:"row",gap:10},delete:{height:52,paddingHorizontal:17,borderRadius:16,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,backgroundColor:"#FFF0F3"},deleteText:{color:"#EF4260",fontSize:11,fontWeight:"900"},cancel:{flex:1,height:52,borderRadius:16,alignItems:"center",justifyContent:"center",backgroundColor:"#EFF1F5"},cancelText:{color:"#66738A",fontSize:11,fontWeight:"900"},savePress:{flex:1.5},save:{height:52,borderRadius:16,alignItems:"center",justifyContent:"center"},saveText:{color:"#FFF",fontSize:11,fontWeight:"900"},
});
