import { LinearGradient } from "expo-linear-gradient";
import { useLocalSearchParams } from "expo-router";
import { StatusBar } from "expo-status-bar";
import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { Glass, PX, ScreenShell } from "@/features/trips/components/TravaPixelUI";
import { useLocalTripWorkspace } from "@/features/trips/hooks/useLocalTripWorkspace";
import { useTripLite } from "@/features/trips/hooks/useTripLite";

const typeStyle: Record<string,{glyph:string,bg:string,fg:string}>={Identity:{glyph:"▤",bg:"#F1EBFF",fg:"#7658F4"},Flight:{glyph:"✈",bg:"#E8F5FF",fg:"#4C9DE9"},Hotel:{glyph:"▥",bg:"#FFF0E7",fg:"#F08A49"},Insurance:{glyph:"✓",bg:"#EAFFF5",fg:"#37B787"},Document:{glyph:"▱",bg:"#F2F4FA",fg:"#66759A"}};
export function DocumentsScreen(){const{tripId:raw}=useLocalSearchParams<{tripId:string}>();const tripId=String(raw??"local-japan");const{trip}=useTripLite(tripId);const{state,addDocument,deleteDocument}=useLocalTripWorkspace(tripId);const[open,setOpen]=useState(false);return <SafeAreaView style={s.safe} edges={["top"]}><StatusBar style="dark"/><ScreenShell tripId={tripId} title={trip.name||"Japan"}><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><View style={s.max}><LinearGradient colors={["#F3EEFF","#FFF1F6","#F2F6FF"]} style={s.hero}><View><Text style={s.heroEyebrow}>LOCAL TRIP VAULT</Text><Text style={s.heroTitle}>Everything important, ready offline.</Text><Text style={s.heroSub}>{state.documents.length} travel documents saved on this device.</Text></View><View style={s.folder}><Text style={s.folderGlyph}>▰</Text><Text style={s.folderStar}>✦</Text></View></LinearGradient><View style={s.topRow}><View><Text style={s.sectionTitle}>Documents</Text><Text style={s.sectionSub}>Private files for your Japan trip</Text></View><Pressable onPress={()=>setOpen(true)}><LinearGradient colors={["#F45C98","#7858F5"]} style={s.add}><Text style={s.addText}>＋ Add Document</Text></LinearGradient></Pressable></View><View style={s.grid}>{state.documents.map(d=>{const cfg=typeStyle[d.type]??typeStyle.Document;return <Glass key={d.id} style={s.card}><View style={[s.icon,{backgroundColor:cfg.bg}]}><Text style={[s.iconGlyph,{color:cfg.fg}]}>{cfg.glyph}</Text></View><View style={s.copy}><Text style={s.title}>{d.title}</Text><Text style={s.meta}>{d.type}  •  {d.size}</Text><Text style={s.updated}>Updated {d.updated}</Text></View><Pressable onPress={()=>deleteDocument(d.id)} style={s.more}><Text style={s.moreText}>•••</Text></Pressable></Glass>})}</View><Glass style={s.note}><Text style={s.noteGlyph}>✓</Text><View><Text style={s.noteTitle}>Stored locally</Text><Text style={s.noteText}>These document entries stay on your device and do not depend on the failing trip workspace API.</Text></View></Glass></View></ScrollView><AddDoc visible={open} onClose={()=>setOpen(false)} onAdd={(title,type)=>{addDocument(title,type);setOpen(false);}}/></ScreenShell></SafeAreaView>}
function AddDoc({visible,onClose,onAdd}:{visible:boolean;onClose():void;onAdd(t:string,type:string):void}){const[title,setTitle]=useState("");const[type,setType]=useState("Document");return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.modal}><Text style={s.modalTitle}>Add local document</Text><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Document name"/><TextInput style={s.input} value={type} onChangeText={setType} placeholder="Type"/><View style={s.modalBtns}><Pressable onPress={onClose} style={s.cancel}><Text style={s.cancelText}>Cancel</Text></Pressable><Pressable onPress={()=>onAdd(title.trim()||"Travel Document",type.trim()||"Document")} style={s.save}><Text style={s.saveText}>Save</Text></Pressable></View></View></View></Modal>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#FFF"},scroll:{padding:22,paddingBottom:130},max:{width:"100%",maxWidth:640,alignSelf:"center",gap:18},hero:{height:220,borderRadius:29,padding:28,justifyContent:"center",overflow:"hidden",boxShadow:"0 16px 38px rgba(95,78,141,.11)"},heroEyebrow:{color:PX.purple,fontSize:11,fontWeight:"900",letterSpacing:1.2},heroTitle:{marginTop:10,maxWidth:380,color:PX.ink,fontSize:28,lineHeight:34,fontWeight:"900"},heroSub:{marginTop:10,color:"#657294",fontSize:12,fontWeight:"600"},folder:{position:"absolute",right:26,bottom:24,width:130,height:112,borderRadius:32,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(255,255,255,.55)",transform:[{rotate:"-6deg"}]},folderGlyph:{color:"#7A5AF5",fontSize:72},folderStar:{position:"absolute",right:12,top:8,color:"#F35B9A",fontSize:24},topRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},sectionTitle:{color:PX.ink,fontSize:22,fontWeight:"900"},sectionSub:{marginTop:4,color:PX.muted,fontSize:11,fontWeight:"600"},add:{height:46,paddingHorizontal:16,borderRadius:16,alignItems:"center",justifyContent:"center"},addText:{color:"#FFF",fontSize:11,fontWeight:"900"},grid:{gap:10},card:{minHeight:92,borderRadius:24,padding:14,flexDirection:"row",alignItems:"center",gap:13},icon:{width:58,height:58,borderRadius:19,alignItems:"center",justifyContent:"center"},iconGlyph:{fontSize:25,fontWeight:"900"},copy:{flex:1},title:{color:PX.ink,fontSize:14,fontWeight:"900"},meta:{marginTop:5,color:"#657294",fontSize:10,fontWeight:"700"},updated:{marginTop:4,color:"#98A0B1",fontSize:9,fontWeight:"600"},more:{width:40,height:40,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:"#F8F9FB"},moreText:{color:"#68758E",fontSize:16,fontWeight:"900"},note:{borderRadius:22,padding:16,flexDirection:"row",gap:12,alignItems:"center",backgroundColor:"#F5FFFA"},noteGlyph:{width:38,height:38,borderRadius:19,textAlign:"center",textAlignVertical:"center",backgroundColor:"#DDF8EA",color:"#2CAF7F",fontSize:20,fontWeight:"900"},noteTitle:{color:"#28785D",fontSize:12,fontWeight:"900"},noteText:{marginTop:3,maxWidth:500,color:"#5B7D70",fontSize:10,lineHeight:15,fontWeight:"600"},backdrop:{flex:1,alignItems:"center",justifyContent:"center",padding:22,backgroundColor:"rgba(12,17,34,.42)"},modal:{width:"100%",maxWidth:420,padding:20,borderRadius:26,backgroundColor:"#FFF"},modalTitle:{color:PX.ink,fontSize:18,fontWeight:"900"},input:{height:50,marginTop:12,paddingHorizontal:14,borderRadius:15,backgroundColor:"#F5F6F9",color:PX.ink},modalBtns:{marginTop:16,flexDirection:"row",gap:8},cancel:{flex:1,height:46,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:"#EEF0F5"},cancelText:{color:PX.muted,fontWeight:"900"},save:{flex:1.5,height:46,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:PX.purple},saveText:{color:"#FFF",fontWeight:"900"}});
