import { Ionicons } from "@expo/vector-icons";
import { Image } from "expo-image";
import { LinearGradient } from "expo-linear-gradient";
import { useLocalSearchParams } from "expo-router";
import { StatusBar } from "expo-status-bar";
import { useEffect, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Glass, PX, ScreenShell } from "../components/TravaPixelUI";
import { useLocalTripWorkspace } from "../hooks/useLocalTripWorkspace";
import { useTripLite } from "../hooks/useTripLite";
import { fetchTripWeather, type TripWeather } from "../utils/weather";

const FALLBACK_RATES: Record<string, number> = { JPY: 2.65, USD: 0.0175, EUR: 0.015, KRW: 23.5, SGD: 0.022, HKD: 0.137, CHF: 0.014, THB: 0.57 };

export function TripDetailsScreen(){
 const {tripId:raw}=useLocalSearchParams<{tripId:string}>(); const tripId=String(raw??"local-japan"); const{trip}=useTripLite(tripId); const{state}=useLocalTripWorkspace(tripId); const spent=state.expenses.reduce((a,e)=>a+e.amount,0);
 const destinationCurrency=currencyFor(`${trip.name||""} ${trip.destination||""}`); const [weather,setWeather]=useState<TripWeather|null>(null); const [amount,setAmount]=useState("1000"); const [rate,setRate]=useState(FALLBACK_RATES[destinationCurrency]??1); const [swapped,setSwapped]=useState(false);
 const anchor=useMemo(()=>[...state.activities].reverse().find(a=>a.latitude!=null&&a.longitude!=null),[state.activities]);
 useEffect(()=>{if(!anchor||anchor.latitude==null||anchor.longitude==null)return;let live=true;void fetchTripWeather(anchor.latitude,anchor.longitude,anchor.locationName).then(v=>live&&setWeather(v));return()=>{live=false}},[anchor]);
 useEffect(()=>{let live=true;void(async()=>{try{const r=await fetch(`https://open.er-api.com/v6/latest/PHP?from=PHP&to=${destinationCurrency}`);if(!r.ok)return;const j=await r.json() as {rates?:Record<string,number>};const n=j.rates?.[destinationCurrency];if(live&&Number.isFinite(n))setRate(Number(n))}catch{}})();return()=>{live=false}},[destinationCurrency]);
 const numeric=Math.max(0,Number(amount.replace(/[^0-9.]/g,""))||0); const converted=swapped?(rate?numeric/rate:0):numeric*rate;
 return <SafeAreaView style={s.safe} edges={["top"]}><StatusBar style="dark"/><ScreenShell tripId={tripId} title={trip.name||"Trip"}><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><View style={s.max}>
   <View style={s.hero}>{trip.coverImageUrl?<Image source={{uri:trip.coverImageUrl}} contentFit="cover" style={StyleSheet.absoluteFill}/>:<LinearGradient colors={["#9BA5B7","#777F8E","#545A65"]} style={StyleSheet.absoluteFill}/>}<LinearGradient colors={["rgba(12,17,27,.03)","rgba(12,17,27,.72)"]} style={StyleSheet.absoluteFill}/><View style={s.heroBottom}><Text style={s.eyebrow}>TRIP OVERVIEW</Text><Text style={s.heroTitle}>{trip.name||"Japan"}</Text><View style={s.heroLocation}><Ionicons name="location-outline" size={15} color="#FFF"/><Text style={s.heroSub}>{trip.destination||"Tokyo, Japan"}</Text></View><View style={s.pills}><Text style={s.pill}>{trip.startDate&&trip.endDate?`${formatDate(trip.startDate)} – ${formatDate(trip.endDate)}`:"Upcoming"}</Text><Text style={s.pill}>{trip.memberCount||1} travelers</Text></View></View></View>
   <View style={s.metrics}><Glass style={s.metric}><Text style={s.metricLabel}>TOTAL BUDGET</Text><Text style={s.metricValue}>₱{state.totalBudget.toLocaleString()}</Text></Glass><Glass style={s.metric}><Text style={s.metricLabel}>SPENT</Text><Text style={s.metricValue}>₱{spent.toLocaleString()}</Text></Glass><Glass style={s.metric}><Text style={s.metricLabel}>READY</Text><Text style={s.metricValue}>{readiness(state)}%</Text></Glass></View>
   <View><Text style={s.sectionTitle}>TRAVA travel assistant</Text><Text style={s.sectionSub}>Useful reminders for this trip, without duplicating your Quick Actions.</Text></View>
   <Glass style={s.assistant}><View style={s.assistantTop}><View style={s.assistantIcon}><Text style={s.assistantEmoji}>{weather?.emoji??"✦"}</Text></View><View style={{flex:1}}><Text style={s.assistantTitle}>{weather?.temperature!=null?`${Math.round(weather.temperature)}°C · ${weather.label}`:"Trip readiness"}</Text><Text style={s.assistantPlace}>{anchor?.locationName||trip.destination||"Destination"}</Text></View></View><Text style={s.assistantTip}>{weather?.tip??"Keep your passport, bookings, payment method, and offline copies of important documents ready before departure."}</Text><View style={s.reminders}>{reminders(state).map(item=><View key={item} style={s.reminder}><Text style={s.check}>✓</Text><Text style={s.reminderText}>{item}</Text></View>)}</View></Glass>
   <Glass style={s.converter}><View style={s.converterHead}><View><Text style={s.converterTitle}>Currency converter</Text><Text style={s.converterSub}>Live rate when available · no paid API key required</Text></View><Text style={s.fx}>FX</Text></View><View style={s.converterRow}><View style={s.currencyBox}><Text style={s.currencyCode}>{swapped?destinationCurrency:"PHP"}</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" style={s.amount}/></View><Pressable onPress={()=>setSwapped(v=>!v)} style={s.swap}><Ionicons name="swap-horizontal" size={20} color="#353A43"/></Pressable><View style={s.currencyBox}><Text style={s.currencyCode}>{swapped?"PHP":destinationCurrency}</Text><Text style={s.converted}>{formatNumber(converted)}</Text></View></View><Text style={s.rateText}>1 {swapped?destinationCurrency:"PHP"} ≈ {swapped?formatNumber(rate?1/rate:0):formatNumber(rate)} {swapped?"PHP":destinationCurrency}</Text></Glass>
 </View></ScrollView></ScreenShell></SafeAreaView>
}
function currencyFor(v:string){const x=v.toLowerCase();if(x.includes("japan")||x.includes("tokyo")||x.includes("osaka"))return"JPY";if(x.includes("korea")||x.includes("seoul"))return"KRW";if(x.includes("hong kong"))return"HKD";if(x.includes("singapore"))return"SGD";if(x.includes("switzerland"))return"CHF";if(x.includes("thailand"))return"THB";if(x.includes("usa")||x.includes("united states"))return"USD";return"USD"}
function readiness(state:ReturnType<typeof useLocalTripWorkspace>["state"]){const checks=state.checklist.filter(i=>i.completed).length;return Math.max(35,Math.min(100,Math.round((checks/Math.max(1,state.checklist.length))*70+30)))}
function reminders(state:ReturnType<typeof useLocalTripWorkspace>["state"]){const out=[] as string[];if(!state.documents.length)out.push("Add offline copies of your key travel documents.");else out.push(`${state.documents.length} travel documents are stored in this trip.`);const open=state.checklist.filter(i=>!i.completed).length;out.push(open?`${open} checklist item${open===1?"":"s"} still need attention.`:"Your checklist is complete.");out.push("Keep some local currency and a backup payment method available.");return out}
function formatDate(v:string){const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{month:"short",day:"numeric"})} function formatNumber(v:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v)}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#FFF"},scroll:{padding:22,paddingBottom:130},max:{width:"100%",maxWidth:640,alignSelf:"center",gap:16},hero:{height:270,borderRadius:30,overflow:"hidden",boxShadow:"0 16px 38px rgba(40,44,54,.14)"},heroBottom:{position:"absolute",left:24,right:24,bottom:22},eyebrow:{color:"#F1F2F4",fontSize:9,fontWeight:"900",letterSpacing:1.2},heroTitle:{marginTop:5,color:"#FFF",fontSize:34,fontWeight:"900"},heroLocation:{marginTop:5,flexDirection:"row",alignItems:"center",gap:5},heroSub:{color:"#FFF",fontSize:13,fontWeight:"700"},pills:{marginTop:12,flexDirection:"row",gap:8},pill:{paddingHorizontal:11,paddingVertical:7,borderRadius:16,backgroundColor:"rgba(255,255,255,.18)",color:"#FFF",fontSize:10,fontWeight:"800"},metrics:{flexDirection:"row",gap:10},metric:{flex:1,minHeight:88,borderRadius:22,padding:14,justifyContent:"center"},metricLabel:{color:"#8D929B",fontSize:8,fontWeight:"900",letterSpacing:.8},metricValue:{marginTop:7,color:PX.ink,fontSize:17,fontWeight:"900"},sectionTitle:{color:PX.ink,fontSize:21,fontWeight:"900"},sectionSub:{marginTop:3,color:PX.muted,fontSize:11,fontWeight:"600"},assistant:{borderRadius:26,padding:18,backgroundColor:"#FBFBFC"},assistantTop:{flexDirection:"row",gap:12,alignItems:"center"},assistantIcon:{width:50,height:50,borderRadius:18,alignItems:"center",justifyContent:"center",backgroundColor:"#F1F2F4"},assistantEmoji:{fontSize:26},assistantTitle:{color:PX.ink,fontSize:15,fontWeight:"900"},assistantPlace:{marginTop:3,color:PX.muted,fontSize:10,fontWeight:"700"},assistantTip:{marginTop:14,color:"#4E535B",fontSize:11,lineHeight:17,fontWeight: "600"},reminders:{marginTop:13,gap:8},reminder:{flexDirection:"row",gap:8,alignItems:"flex-start"},check:{color:"#4C8E72",fontSize:12,fontWeight:"900"},reminderText:{flex:1,color:"#626770",fontSize:10,lineHeight:15,fontWeight: "600"},converter:{borderRadius:26,padding:18},converterHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},converterTitle:{color:PX.ink,fontSize:17,fontWeight:"900"},converterSub:{marginTop:3,color:PX.muted,fontSize:9,fontWeight:"600"},fx:{width:38,height:38,borderRadius:19,textAlign:"center",textAlignVertical:"center",backgroundColor:"#F1F2F4",color:"#535860",fontSize:10,fontWeight:"900"},converterRow:{marginTop:16,flexDirection:"row",alignItems:"center",gap:8},currencyBox:{flex:1,minHeight:76,padding:12,borderRadius:20,backgroundColor:"#F7F8FA",borderWidth:1,borderColor:"#E5E7EB"},currencyCode:{color:"#777C84",fontSize:9,fontWeight:"900"},amount:{marginTop:6,color:PX.ink,fontSize:18,fontWeight:"900"},converted:{marginTop:8,color:PX.ink,fontSize:18,fontWeight:"900"},swap:{width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center",backgroundColor:"#FFF",borderWidth:1,borderColor:"#E4E6EA"},rateText:{marginTop:10,color:PX.muted,fontSize:9,fontWeight: "600"}});
