import { StyleSheet, View } from "react-native";
import { WebView } from "react-native-webview";
import type { TripMapSurfaceProps } from "./TripMapSurface.types";
export function TripMapSurface({ activities, selectedActivityId, onSelectActivity, height = 360 }: TripMapSurfaceProps) {
  const html = makeMapHtml(activities, selectedActivityId);
  return <View style={[styles.wrap, { height }]}><WebView originWhitelist={["*"]} source={{ html }} javaScriptEnabled domStorageEnabled onMessage={(event) => { try { const p = JSON.parse(event.nativeEvent.data) as { type?: string; id?: string }; if (p.type === "trava-select" && p.id) onSelectActivity?.(p.id); } catch {} }} style={styles.web}/></View>;
}
function makeMapHtml(activities: TripMapSurfaceProps["activities"], selected: string | null | undefined) {
  const points = activities.filter((a) => a.latitude != null && a.longitude != null).map((a) => ({ ...a, selected: a.id === selected }));
  const data = JSON.stringify(points).replace(/</g, "\\u003c");
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>*{box-sizing:border-box}html,body,#map{width:100%;height:100%;margin:0}.leaflet-tile{filter:saturate(.72) brightness(1.10) contrast(.88) hue-rotate(7deg)}.leaflet-control-attribution{display:none}.pin{width:38px;height:38px;border-radius:19px;background:#fff;display:flex;align-items:center;justify-content:center;font-size:18px;box-shadow:0 7px 18px rgba(74,66,111,.2)}.pin.sel{width:44px;height:44px;border-radius:22px;background:linear-gradient(135deg,#f45d96,#7757f6)}.leaflet-control-zoom{border:0!important;border-radius:18px!important;overflow:hidden}.leaflet-control-zoom a{width:44px!important;height:44px!important;line-height:44px!important;border:0!important;background:#fff!important;color:#15203b!important}</style></head><body><div id="map"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const pts=${data};const map=L.map('map',{zoomControl:true,attributionControl:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);const glyph={flight:'✈️',stay:'🏨',food:'🍜',sightseeing:'🗼',transport:'🚆',shopping:'🛍️',meeting:'💼',other:'📍'};const ll=[];pts.forEach(p=>{const icon=L.divIcon({className:'',html:'<div class="pin '+(p.selected?'sel':'')+'">'+(glyph[p.category]||'📍')+'</div>',iconSize:[44,44],iconAnchor:[22,22]});const m=L.marker([p.latitude,p.longitude],{icon}).addTo(map);m.on('click',()=>window.ReactNativeWebView&&window.ReactNativeWebView.postMessage(JSON.stringify({type:'trava-select',id:p.id})));ll.push([p.latitude,p.longitude]);});if(ll.length>1)L.polyline(ll,{color:'#8262f5',weight:2.5,dashArray:'7 8',opacity:.85}).addTo(map);if(ll.length)map.fitBounds(L.latLngBounds(ll).pad(.30));else map.setView([35.68,139.65],5);</script></body></html>`;
}
const styles = StyleSheet.create({ wrap: { overflow: "hidden", borderRadius: 27, backgroundColor: "#EEF6FF", borderWidth: 1, borderColor: "rgba(255,255,255,.95)", boxShadow: "0 16px 34px rgba(68,74,110,.10)" }, web: { flex: 1, backgroundColor: "transparent" } });
