import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform, Share } from "react-native";
import type { TripExpense, TripMember } from "@trava/shared";

export async function exportTripInvoice({ tripName, currency, expenses, members }: { tripName: string; currency: string; expenses: TripExpense[]; members: TripMember[] }) {
  const shared = expenses.filter((x) => x.splitMethod !== "payer_only");
  const total = shared.reduce((sum, x) => sum + x.amount, 0);
  const accepted = members.filter((m) => m.status === "accepted");
  const perPerson = accepted.length ? total / accepted.length : total;
  const rows = shared.map((e) => `<tr><td>${escapeHtml(e.title)}</td><td>${escapeHtml(e.paidByName)}</td><td>${escapeHtml(e.expenseDate)}</td><td style="text-align:right">${money(e.amount,currency)}</td></tr>`).join("");
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#111827;padding:30px}h1{font-size:28px;margin:0}p{color:#6b7280}.hero{padding:22px;border-radius:22px;background:linear-gradient(135deg,#f5efff,#fff0f5)}.metrics{display:flex;gap:12px;margin-top:18px}.metric{flex:1;padding:14px;border:1px solid #eceaf4;border-radius:14px}table{width:100%;border-collapse:collapse;margin-top:24px}td,th{padding:10px;border-bottom:1px solid #eee;text-align:left;font-size:12px}.total{font-size:22px;font-weight:800}.muted{font-size:11px;color:#7b8090}</style></head><body><div class="hero"><h1>Trip Invoice — ${escapeHtml(tripName)}</h1><p>Generated by TRAVA</p><div class="metrics"><div class="metric"><div class="muted">Total shared</div><div class="total">${money(total,currency)}</div></div><div class="metric"><div class="muted">Per person</div><div class="total">${money(perPerson,currency)}</div></div></div></div><table><thead><tr><th>Expense</th><th>Paid by</th><th>Date</th><th style="text-align:right">Amount</th></tr></thead><tbody>${rows || '<tr><td colspan="4">No shared expenses yet.</td></tr>'}</tbody></table></body></html>`;
  if (Platform.OS === "web") {
    const w = (globalThis as typeof globalThis & { open?: typeof window.open }).open?.("", "_blank");
    if (w) { w.document.write(html); w.document.close(); setTimeout(() => w.print(), 200); }
    return;
  }
  const file = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(file.uri, { mimeType: "application/pdf", dialogTitle: `${tripName} invoice` });
}

export async function sendSettlementReminder({ tripName, total, currency, people }: { tripName: string; total: number; currency: string; people: number }) {
  await Share.share({ message: `TRAVA reminder for ${tripName}: shared expenses total ${money(total,currency)} across ${people} traveler${people === 1 ? "" : "s"}. Open the trip to review your balance.` });
}

function money(v:number,c:string){const n=Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});return c==="PHP"||c==="₱"?`₱${n}`:`${c} ${n}`;}
function escapeHtml(v:string){return v.replace(/[&<>"']/g,(m)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m] ?? m));}
