import { Image } from "expo-image";
import { LinearGradient } from "expo-linear-gradient";
import { type Href, useLocalSearchParams, useRouter } from "expo-router";
import { StatusBar } from "expo-status-bar";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Glass, PX, ScreenShell, Soft3DIcon } from "../components/TravaPixelUI";
import { useLocalTripWorkspace } from "../hooks/useLocalTripWorkspace";
import { useTripLite } from "../hooks/useTripLite";

const actions=[["Itinerary","Daily plans","itinerary","▦",["#FFB2C5","#F6668D"]],["Budget","Track your budget","budget","▱",["#A5F0D0","#57D5A1"]],["Expenses","Add & manage","expenses","▤",["#FFD0A4","#FFA35C"]],["Checklist","Stay organized","checklist","✓",["#CCACFF","#9C6EF6"]],["Documents","Travel docs","documents","▰",["#B8DBFF","#74B6F7"]]] as const;
export function TripDetailsScreen(){const{tripId:raw}=useLocalSearchParams<{tripId:string}>();const tripId=String(raw??"local-japan");const{trip}=useTripLite(tripId);const{state}=useLocalTripWorkspace(tripId);const router=useRouter();const spent=state.expenses.reduce((a,e)=>a+e.amount,0);return <SafeAreaView style={s.safe} edges={["top"]}><StatusBar style="dark"/><ScreenShell tripId={tripId} title={trip.name||"Japan"}><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><View style={s.max}><View style={s.hero}>{trip.coverImageUrl?<Image source={{uri:trip.coverImageUrl}} contentFit="cover" style={StyleSheet.absoluteFillObject}/>:<LinearGradient colors={["#AFB7FF","#F1B2D5","#FFD8B4"]} style={StyleSheet.absoluteFillObject}/>}<LinearGradient colors={["rgba(14,22,48,.05)","rgba(14,22,48,.68)"]} style={StyleSheet.absoluteFillObject}/><View style={s.heroBottom}><Text style={s.eyebrow}>JAPAN TRIP</Text><Text style={s.heroTitle}>{trip.name||"Japan"}</Text><Text style={s.heroSub}>⌖ {trip.destination||"Tokyo, Japan"}</Text><View style={s.pills}><Text style={s.pill}>Mar 10 – Mar 17</Text><Text style={s.pill}>{trip.memberCount||3} travelers</Text></View></View></View><View style={s.metrics}><Glass style={s.metric}><Text style={s.metricLabel}>TOTAL BUDGET</Text><Text style={s.metricValue}>₱{state.totalBudget.toLocaleString()}</Text></Glass><Glass style={s.metric}><Text style={s.metricLabel}>SPENT</Text><Text style={s.metricValue}>₱{spent.toLocaleString()}</Text></Glass><Glass style={s.metric}><Text style={s.metricLabel}>READY</Text><Text style={s.metricValue}>78%</Text></Glass></View><View><Text style={s.sectionTitle}>Plan & Manage</Text><Text style={s.sectionSub}>Everything for this trip in one place.</Text></View><View style={s.grid}>{actions.map(([label,sub,suffix,glyph,colors],i)=><Pressable key={label} onPress={()=>router.push(`/trip/${tripId}/${suffix}` as Href)} style={[s.action,i<2&&s.actionWide]}><View style={s.actionCopy}><Text style={s.actionTitle}>{label}</Text><Text style={s.actionSub}>{sub}</Text></View><Soft3DIcon colors={colors as readonly[string,string]} glyph={glyph} size={58}/></Pressable>)}</View><Glass style={s.localCard}><Text style={s.localTitle}>Local-first trip workspace</Text><Text style={s.localText}>Itinerary, budget, expenses, checklist and documents load from on-device state first, so these tabs remain usable even while the legacy remote trip schema is being repaired.</Text></Glass></View></ScrollView></ScreenShell></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#FFF"},scroll:{padding:22,paddingBottom:130},max:{width:"100%",maxWidth:640,alignSelf:"center",gap:16},hero:{height:290,borderRadius:30,overflow:"hidden",boxShadow:"0 16px 38px rgba(60,61,92,.14)"},heroBottom:{position:"absolute",left:24,right:24,bottom:22},eyebrow:{color:"#F0EEFF",fontSize:10,fontWeight:"900",letterSpacing:1.2},heroTitle:{marginTop:5,color:"#FFF",fontSize:34,fontWeight:"900"},heroSub:{marginTop:5,color:"#F7F7FF",fontSize:13,fontWeight:"700"},pills:{marginTop:12,flexDirection:"row",gap:8},pill:{paddingHorizontal:11,paddingVertical:7,borderRadius:16,backgroundColor:"rgba(255,255,255,.18)",color:"#FFF",fontSize:10,fontWeight:"800"},metrics:{flexDirection:"row",gap:10},metric:{flex:1,minHeight:88,borderRadius:22,padding:14,justifyContent:"center"},metricLabel:{color:"#8D96AA",fontSize:8,fontWeight:"900",letterSpacing:.8},metricValue:{marginTop:7,color:PX.ink,fontSize:17,fontWeight:"900"},sectionTitle:{color:PX.ink,fontSize:21,fontWeight:"900"},sectionSub:{marginTop:3,color:PX.muted,fontSize:11,fontWeight:"600"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},action:{width:"31.5%",minWidth:170,minHeight:104,padding:15,borderRadius:24,flexGrow:1,flexDirection:"row",alignItems:"center",justifyContent:"space-between",backgroundColor:"#FFF",borderWidth:1,borderColor:"#ECEEF4",boxShadow:"0 10px 24px rgba(70,74,104,.06)"},actionWide:{width:"48%"},actionCopy:{flex:1,minWidth:0},actionTitle:{color:PX.ink,fontSize:14,fontWeight:"900"},actionSub:{marginTop:4,color:PX.muted,fontSize:10,fontWeight:"600"},localCard:{borderRadius:24,padding:18,backgroundColor:"#F7FFFB"},localTitle:{color:"#28785D",fontSize:13,fontWeight:"900"},localText:{marginTop:5,color:"#5E796F",fontSize:10,lineHeight:16,fontWeight:"600"}});
