import { Ionicons } from "@expo/vector-icons";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { type Href, useRouter } from "expo-router";
import type { TripSummary } from "@trava/shared";

import { listTrips } from "@/features/trips/api/trips.api";
import { addDiscoverPlaceToItinerary } from "../utils/add-place-to-itinerary";
import type { DiscoverPlace } from "./DiscoverMap.types";

export function AddToItinerarySheet({ place, visible, onClose }: { place:DiscoverPlace|null;visible:boolean;onClose():void }) {
  const router=useRouter(); const [trips,setTrips]=useState<TripSummary[]>([]);const [tripId,setTripId]=useState<string|null>(null);const [day,setDay]=useState(1);const [time,setTime]=useState("09:00");const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);
  useEffect(()=>{if(!visible)return;setDay(1);setLoading(true);void listTrips().then((items)=>{const active=items.filter((trip)=>trip.status!=="completed");setTrips(active);setTripId(active[0]?.id??null);}).catch(()=>setTrips([])).finally(()=>setLoading(false));},[visible]);
  const trip=useMemo(()=>trips.find((item)=>item.id===tripId)??null,[trips,tripId]);const days=Math.max(1,Math.min(31,trip?.numberOfDays||1));
  const add=async()=>{if(!place||!trip)return;setSaving(true);try{const result=await addDiscoverPlaceToItinerary({place,trip,dayNumber:day,startTime:time});onClose();Alert.alert("Added to itinerary",`${place.name} was added to ${trip.name}, Day ${day}.${result.serverSynced?"":" Saved locally and will remain in this workspace."}`);}catch{Alert.alert("Could not add place","Try again in a moment.");}finally{setSaving(false);}};
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.head}><View style={{flex:1}}><Text style={styles.eyebrow}>ADD TO ITINERARY</Text><Text numberOfLines={2} style={styles.title}>Add {place?.name||"place"}</Text></View><Pressable onPress={onClose} style={styles.close}><Ionicons name="close" size={19} color="#59647A"/></Pressable></View>
    {loading?<View style={styles.center}><ActivityIndicator color="#795FDF"/><Text style={styles.muted}>Loading your trips…</Text></View>:!trips.length?<View style={styles.center}><Ionicons name="airplane-outline" size={28} color="#846DDE"/><Text style={styles.emptyTitle}>You don’t have an active trip yet.</Text><Pressable onPress={()=>{onClose();router.push("/(traveler)/(tabs)/trips" as Href);}} style={styles.primary}><Text style={styles.primaryText}>Create or open a trip</Text></Pressable></View>:<>
      <Text style={styles.label}>SELECT TRIP</Text><ScrollView style={{maxHeight:190}}>{trips.map((item)=><Pressable key={item.id} onPress={()=>{setTripId(item.id);setDay(1);}} style={[styles.trip,item.id===tripId&&styles.tripOn]}><View style={{flex:1}}><Text style={styles.tripName}>{item.name}</Text><Text style={styles.tripSub}>{item.destination}</Text></View><Ionicons name={item.id===tripId?"checkmark-circle":"ellipse-outline"} size={20} color={item.id===tripId?"#765DDF":"#AFB5C1"}/></Pressable>)}</ScrollView>
      <Text style={styles.label}>SELECT DAY</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.days}>{Array.from({length:days},(_,i)=>i+1).map((value)=><Pressable key={value} onPress={()=>setDay(value)} style={[styles.day,value===day&&styles.dayOn]}><Text style={[styles.dayText,value===day&&styles.dayTextOn]}>Day {value}</Text></Pressable>)}</ScrollView>
      <Text style={styles.label}>TIME</Text><View style={styles.time}><Ionicons name="time-outline" size={17} color="#7D8799"/><TextInput value={time} onChangeText={setTime} maxLength={5} style={styles.timeInput}/><Text style={styles.timeHint}>24-hour</Text></View>
      <Pressable disabled={saving||!trip} onPress={()=>void add()} style={[styles.primary,{marginTop:16},saving&&{opacity:.6}]}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Add to {trip?.name}</Text>}</Pressable>
    </>}
  </View></View></Modal>;
}
const styles=StyleSheet.create({backdrop:{flex:1,justifyContent:"flex-end",backgroundColor:"rgba(21,27,43,.3)",padding:12},sheet:{width:"100%",maxWidth:600,alignSelf:"center",maxHeight:"84%",padding:17,borderRadius:28,backgroundColor:"#fff"},head:{flexDirection:"row",alignItems:"flex-start",gap:10},eyebrow:{color:"#8267E2",fontSize:7.5,fontWeight:"900",letterSpacing:.8},title:{marginTop:4,color:"#202943",fontSize:19,fontWeight:"900"},close:{width:38,height:38,borderRadius:19,alignItems:"center",justifyContent:"center",backgroundColor:"#F5F6F8"},label:{marginTop:16,marginBottom:7,color:"#8B76D9",fontSize:7.5,fontWeight:"900",letterSpacing:.7},trip:{minHeight:58,flexDirection:"row",alignItems:"center",gap:8,padding:10,borderRadius:16,borderWidth:1,borderColor:"#ECECF0",marginBottom:6},tripOn:{backgroundColor:"#F6F2FF",borderColor:"#D5C9F7"},tripName:{color:"#2B344C",fontSize:10.5,fontWeight:"900"},tripSub:{marginTop:2,color:"#8891A3",fontSize:8.2,fontWeight:"600"},days:{gap:7},day:{minHeight:35,paddingHorizontal:12,alignItems:"center",justifyContent:"center",borderRadius:14,backgroundColor:"#F6F6F9"},dayOn:{backgroundColor:"#8065E2"},dayText:{color:"#687286",fontSize:8.5,fontWeight:"900"},dayTextOn:{color:"#fff"},time:{height:45,flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:12,borderRadius:15,backgroundColor:"#F8F8FA",borderWidth:1,borderColor:"#EAEBEF"},timeInput:{flex:1,color:"#2C344B",fontSize:10,fontWeight:"800"},timeHint:{color:"#9AA1B0",fontSize:7.5,fontWeight:"700"},center:{minHeight:180,alignItems:"center",justifyContent:"center",gap:8},muted:{color:"#8A93A4",fontSize:9,fontWeight:"600"},emptyTitle:{color:"#30394F",fontSize:11,fontWeight:"900"},primary:{minHeight:43,paddingHorizontal:16,alignItems:"center",justifyContent:"center",borderRadius:15,backgroundColor:"#8064E3"},primaryText:{color:"#fff",fontSize:9.5,fontWeight:"900"}});
