import { LinearGradient } from "expo-linear-gradient";
import { Tabs } from "expo-router";
import { Pressable, StyleSheet, Text, View, type ColorValue } from "react-native";

const ICONS={home:"⌂",explore:"◉",trips:"▣",ai:"✣",profile:"♙"} as const;
type N=keyof typeof ICONS;
function I({name,color,focused}:{name:N;color:ColorValue;focused:boolean}){if(name==="ai")return <LinearGradient colors={["#B7CAFF","#8C73FA","#F18BC8"]} style={s.ai}><Text style={s.aiIcon}>✣</Text><Text style={s.aiText}>AI</Text></LinearGradient>;return <View style={[s.iWrap,focused&&s.iOn]}><Text style={[s.icon,{color}]}>{ICONS[name]}</Text></View>}
export default function TravelerTabsLayout(){return <Tabs initialRouteName="home" screenOptions={{headerShown:false,tabBarHideOnKeyboard:true,tabBarActiveTintColor:"#7153F4",tabBarInactiveTintColor:"#34486F",tabBarLabelStyle:s.label,tabBarItemStyle:s.item,tabBarStyle:s.bar,sceneStyle:s.scene}}><Tabs.Screen name="home" options={{title:"Home",tabBarIcon:({color,focused})=><I name="home" color={color} focused={focused}/>}}/><Tabs.Screen name="explore" options={{title:"Discover",tabBarIcon:({color,focused})=><I name="explore" color={color} focused={focused}/>}}/><Tabs.Screen name="ai" options={{title:"",tabBarIcon:({color,focused})=><I name="ai" color={color} focused={focused}/>}}/><Tabs.Screen name="trips" options={{title:"Trips",tabBarIcon:({color,focused})=><I name="trips" color={color} focused={focused}/>}}/><Tabs.Screen name="profile" options={{title:"Profile",tabBarIcon:({color,focused})=><I name="profile" color={color} focused={focused}/>}}/></Tabs>}
const s=StyleSheet.create({scene:{backgroundColor:"#FFF"},bar:{position:"absolute",left:18,right:18,bottom:14,height:78,borderRadius:39,borderTopWidth:0,backgroundColor:"rgba(255,255,255,.96)",boxShadow:"0 -2px 28px rgba(80,73,118,.12)",paddingTop:7,paddingBottom:7},item:{paddingVertical:0},label:{fontSize:10,lineHeight:12,fontWeight:"700"},iWrap:{width:42,height:34,borderRadius:17,alignItems:"center",justifyContent:"center"},iOn:{backgroundColor:"#F0EBFF"},icon:{fontSize:24,lineHeight:27,fontWeight:"700"},ai:{width:86,height:58,borderRadius:23,marginTop:-15,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:6,borderWidth:1,borderColor:"rgba(255,255,255,.9)",boxShadow:"0 12px 26px rgba(125,86,230,.22)"},aiIcon:{color:"#FFF",fontSize:22},aiText:{color:"#FFF",fontSize:18,fontWeight:"800"}})
