import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { type Href, useRouter } from "expo-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { useAuth } from "@/features/auth/hooks/useAuth";
import { AddToItinerarySheet } from "@/features/explore/components/AddToItinerarySheet";
import type { DiscoverPlace } from "@/features/explore/components/DiscoverMap.types";
import { AiComposer } from "../components/AiComposer";
import { AiHeader } from "../components/AiHeader";
import { AiMessageBubble } from "../components/AiMessageBubble";
import { AiPreferencePanel } from "../components/AiPreferencePanel";
import { AiQuickPrompts, DEFAULT_QUICK_PROMPTS } from "../components/AiQuickPrompts";
import { AiTypingIndicator } from "../components/AiTypingIndicator";
import { useAiConversation } from "../hooks/useAiConversation";
import { useAiPreferences } from "../hooks/useAiPreferences";
import type { AiResolvedPlace } from "../types/ai.types";

export function AiScreen(){
  const router=useRouter();const {width}=useWindowDimensions();const {user}=useAuth();const prefs=useAiPreferences();const chat=useAiConversation(user?.id,prefs.preferences);const [input,setInput]=useState("");const [addPlace,setAddPlace]=useState<DiscoverPlace|null>(null);const scrollRef=useRef<ScrollView>(null);const wide=width>=960;
  useEffect(()=>{requestAnimationFrame(()=>scrollRef.current?.scrollToEnd({animated:true}));},[chat.messages.length,chat.sending]);
  const lastAssistant=useMemo(()=>[...chat.messages].reverse().find((item)=>item.role==="assistant"),[chat.messages]);
  const quickReplies=lastAssistant?.quickReplies?.length?lastAssistant.quickReplies:DEFAULT_QUICK_PROMPTS;
  const submit=async(text=input)=>{const value=text.trim();if(!value||chat.sending)return;setInput("");const ok=await chat.send(value);if(!ok&&text===input)setInput(value);};
  const openMap=(value:AiResolvedPlace)=>{const p=value.place;router.push(`/(traveler)/(tabs)/explore?focusLat=${p.latitude}&focusLon=${p.longitude}&focusName=${encodeURIComponent(p.name)}&focusSubtitle=${encodeURIComponent(p.subtitle)}&focusProviderId=${encodeURIComponent(p.providerId ?? p.id)}&focusCategory=${encodeURIComponent(p.category)}` as Href);};
  return <SafeAreaView style={styles.safe} edges={["top"]}><LinearGradient colors={["#FCFCFF","#FFF8FC","#F8FBFF"]} style={StyleSheet.absoluteFill}/><View style={styles.root}><View style={styles.max}><AiHeader onNewChat={chat.newChat}/><View style={[styles.workspace,wide&&styles.workspaceWide]}>
    {wide?<View style={styles.side}><AiPreferencePanel preferences={prefs.preferences} expanded={prefs.expanded} onExpanded={prefs.setExpanded} onUpdate={prefs.update}/><View style={styles.sideNote}><Ionicons name="shield-checkmark-outline" size={16} color="#7962D8"/><Text style={styles.sideNoteText}>Travel-only assistant. Place cards are resolved against real map data before they appear.</Text></View></View>:null}
    <View style={styles.chatCard}>{!wide?<AiPreferencePanel preferences={prefs.preferences} expanded={prefs.expanded} onExpanded={prefs.setExpanded} onUpdate={prefs.update}/>:null}<ScrollView ref={scrollRef} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.messages}>
      {!chat.messages.length?<Welcome/>:chat.messages.map((message)=><AiMessageBubble key={message.id} message={message} onMap={openMap} onAdd={(value)=>setAddPlace(value.place)}/>)}
      {chat.sending?<AiTypingIndicator/>:null}
      {chat.error?<View style={styles.error}><Ionicons name="cloud-offline-outline" size={17} color="#916F7D"/><View style={{flex:1}}><Text style={styles.errorText}>{chat.error}</Text><Text style={styles.errorSub}>Technical details are intentionally kept out of your conversation.</Text></View>{chat.lastFailed?<Pressable disabled={chat.sending} onPress={()=>void chat.retry()} style={styles.retry}><Text style={styles.retryText}>Retry</Text></Pressable>:null}</View>:null}
    </ScrollView><View style={styles.bottom}><AiQuickPrompts prompts={quickReplies} disabled={chat.sending} onPrompt={(prompt)=>void submit(prompt)}/><AiComposer value={input} onChange={setInput} sending={chat.sending} onSend={()=>void submit()}/><Text style={styles.disclaimer}>TRAVA can help plan travel, but live prices, visa rules, hours and availability should still be verified when they matter.</Text></View></View>
  </View></View></View><AddToItinerarySheet place={addPlace} visible={Boolean(addPlace)} onClose={()=>setAddPlace(null)}/></SafeAreaView>;
}
function Welcome(){return <View style={styles.welcome}><View style={styles.welcomeAvatar}><Text style={styles.welcomeStar}>✦</Text></View><Text style={styles.welcomeKicker}>TRAVA AI</Text><Text style={styles.welcomeTitle}>Hi there! 👋</Text><Text style={styles.welcomeText}>I’m your travel assistant. Where are you thinking of going?</Text><View style={styles.capabilities}><Capability icon="map-outline" text="Build realistic itineraries"/><Capability icon="restaurant-outline" text="Find food and places"/><Capability icon="wallet-outline" text="Plan a travel budget"/><Capability icon="train-outline" text="Think through transport"/></View></View>}
function Capability({icon,text}:{icon:React.ComponentProps<typeof Ionicons>["name"];text:string}){return <View style={styles.capability}><Ionicons name={icon} size={14} color="#8066DD"/><Text style={styles.capabilityText}>{text}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#FBFCFF"},root:{flex:1,paddingHorizontal:14},max:{flex:1,width:"100%",maxWidth:1180,alignSelf:"center"},workspace:{flex:1,minHeight:0,gap:12,paddingBottom:10},workspaceWide:{flexDirection:"row",alignItems:"stretch"},side:{width:330,gap:10},sideNote:{flexDirection:"row",gap:8,padding:12,borderRadius:18,backgroundColor:"rgba(255,255,255,.82)",borderWidth:1,borderColor:"#EBE8F1"},sideNoteText:{flex:1,color:"#7F8797",fontSize:8,lineHeight:12,fontWeight:"600"},chatCard:{flex:1,minWidth:0,overflow:"hidden",borderRadius:26,backgroundColor:"rgba(251,251,254,.78)",borderWidth:1,borderColor:"#E9E8EF"},messages:{padding:12,paddingBottom:18},bottom:{paddingHorizontal:10,paddingBottom:9,backgroundColor:"rgba(251,251,254,.96)",borderTopWidth:1,borderTopColor:"#ECEBF0"},disclaimer:{marginTop:6,color:"#A0A5B0",fontSize:6.8,lineHeight:10,textAlign:"center",fontWeight:"600"},welcome:{minHeight:300,alignItems:"center",justifyContent:"center",paddingVertical:28,paddingHorizontal:18},welcomeAvatar:{width:54,height:54,borderRadius:20,alignItems:"center",justifyContent:"center",backgroundColor:"#EEE9FF",borderWidth:1,borderColor:"#DDD3FA"},welcomeStar:{color:"#765DDF",fontSize:25,fontWeight:"900"},welcomeKicker:{marginTop:12,color:"#8065DF",fontSize:7,fontWeight:"900",letterSpacing:.9},welcomeTitle:{marginTop:5,color:"#202943",fontSize:21,fontWeight:"900"},welcomeText:{marginTop:5,maxWidth:460,color:"#7E8799",fontSize:10,lineHeight:15,textAlign:"center",fontWeight:"600"},capabilities:{marginTop:17,width:"100%",maxWidth:520,flexDirection:"row",flexWrap:"wrap",gap:7,justifyContent:"center"},capability:{minHeight:34,flexDirection:"row",alignItems:"center",gap:5,paddingHorizontal:10,borderRadius:14,backgroundColor:"#fff",borderWidth:1,borderColor:"#E9E8EE"},capabilityText:{color:"#6D7587",fontSize:7.8,fontWeight:"800"},error:{marginTop:11,flexDirection:"row",alignItems:"center",gap:8,padding:11,borderRadius:16,backgroundColor:"#FFF7F8",borderWidth:1,borderColor:"#F0DFE3"},errorText:{color:"#765E68",fontSize:9,fontWeight:"800"},errorSub:{marginTop:2,color:"#9A8790",fontSize:7.2,fontWeight:"600"},retry:{minHeight:32,paddingHorizontal:10,alignItems:"center",justifyContent:"center",borderRadius:12,backgroundColor:"#F1E8EC"},retryText:{color:"#7D5F6D",fontSize:7.8,fontWeight:"900"}});
