import { Ionicons } from "@expo/vector-icons";
import { Image } from "expo-image";
import { LinearGradient } from "expo-linear-gradient";
import { type Href, useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { hydrateVerifiedPlaceImages } from "@/features/maps/utils/place-photo";
import { searchNearbyPlaces, worldResultToDiscoverPlace } from "@/features/maps/utils/world-place-search";
import type { DiscoverPlace } from "../components/DiscoverMap.types";
import { EXPLORE_CATEGORIES, DISCOVERY_RADII, categoryApi, formatDistance, type ExploreCategory } from "../data/explore-categories";
import { TOUR_PACKAGE_PREVIEWS } from "../preview/tour-packages.preview";
import { TRAVEL_AGENCY_PREVIEWS } from "../preview/travel-agencies.preview";

export function ExploreAllScreen() {
  const router=useRouter();const params=useLocalSearchParams<{section?:string;category?:string;lat?:string;lon?:string;label?:string;radius?:string}>();const {width}=useWindowDimensions();
  const section=params.section==="packages"||params.section==="agencies"?params.section:"picks";
  const initialCategory=normalizeCategory(params.category);const [category,setCategory]=useState<ExploreCategory>(initialCategory);const [radius,setRadius]=useState(Number(params.radius)||8000);const [query,setQuery]=useState("");const [places,setPlaces]=useState<DiscoverPlace[]>([]);const [loading,setLoading]=useState(section==="picks");const [error,setError]=useState(false);const [version,setVersion]=useState(0);
  const lat=finite(params.lat,10.3157),lon=finite(params.lon,123.8854),label=typeof params.label==="string"?decodeURIComponent(params.label):"selected area";const center={latitude:lat,longitude:lon};
  useEffect(()=>{if(section!=="picks")return;const controller=new AbortController();setLoading(true);setError(false);void searchNearbyPlaces(categoryApi(category),lat,lon,50,{radiusMeters:radius,signal:controller.signal}).then((items)=>{const mapped=items.map((item)=>worldResultToDiscoverPlace(item,center));setPlaces(mapped);void hydrateVerifiedPlaceImages(mapped.slice(0,20),controller.signal).then((hydrated)=>{const by=new Map(hydrated.map((p)=>[p.id,p]));setPlaces((current)=>current.map((p)=>by.get(p.id)??p));}).catch(()=>{});}).catch(()=>{if(!controller.signal.aborted)setError(true);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[section,category,lat,lon,radius,version]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return !q?places:places.filter((p)=>`${p.name} ${p.subtitle} ${p.category}`.toLowerCase().includes(q));},[places,query]);
  const columns=width>=1100?4:width>=760?3:width>=500?2:1;
  const focus=(p:DiscoverPlace)=>router.replace(`/(traveler)/(tabs)/explore?focusLat=${p.latitude}&focusLon=${p.longitude}&focusName=${encodeURIComponent(p.name)}&focusSubtitle=${encodeURIComponent(p.subtitle)}&focusProviderId=${encodeURIComponent(p.providerId ?? p.id)}&focusCategory=${encodeURIComponent(p.category)}` as Href);
  const title=section==="picks"?`Places around ${label}`:section==="packages"?"Tour Packages":"Travel Agencies";
  return <SafeAreaView style={styles.safe} edges={["top"]}><LinearGradient colors={["#FBFCFF","#FFF9FD","#F9FBFF"]} style={StyleSheet.absoluteFill}/><ScrollView contentContainerStyle={styles.content}><View style={styles.max}>
    <View style={styles.head}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={19} color="#445069"/></Pressable><View style={{flex:1}}><Text style={styles.kicker}>{section==="picks"?"REAL PLACE DISCOVERY":"MARKETPLACE PREVIEW"}</Text><Text style={styles.title}>{title}</Text><Text style={styles.sub}>{section==="picks"?"Results use the exploration area—not mandatory GPS.":"These cards demonstrate the future marketplace and are not live bookable inventory."}</Text></View></View>
    <View style={styles.search}><Ionicons name="search-outline" size={18} color="#818B9D"/><TextInput value={query} onChangeText={setQuery} placeholder={`Search ${section==="picks"?"places":"preview cards"}…`} placeholderTextColor="#9AA2B1" style={styles.input}/>{query?<Pressable onPress={()=>setQuery("")}><Ionicons name="close-circle" size={18} color="#A4ABB8"/></Pressable>:null}</View>
    {section==="picks"?<><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{EXPLORE_CATEGORIES.map((item)=><Pressable key={item.name} onPress={()=>setCategory(item.name)} style={[styles.chip,item.name===category&&styles.chipOn]}><Ionicons name={item.icon} size={13} color={item.name===category?"#fff":"#606A7D"}/><Text style={[styles.chipText,item.name===category&&styles.chipTextOn]}>{item.name}</Text></Pressable>)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.radii}>{DISCOVERY_RADII.map((value)=><Pressable key={value} onPress={()=>setRadius(value)} style={[styles.radius,value===radius&&styles.radiusOn]}><Text style={[styles.radiusText,value===radius&&styles.radiusTextOn]}>{value/1000} km</Text></Pressable>)}</ScrollView></>:null}
    {loading?<View style={styles.state}><ActivityIndicator color="#8064E3"/><Text style={styles.stateText}>Loading real places…</Text></View>:error?<View style={styles.state}><Ionicons name="cloud-offline-outline" size={26} color="#8067DE"/><Text style={styles.stateTitle}>We couldn’t load places right now.</Text><Pressable onPress={()=>setVersion((v)=>v+1)} style={styles.retry}><Text style={styles.retryText}>Retry</Text></Pressable></View>:null}
    {!loading&&!error&&section==="picks"?<View style={styles.grid}>{filtered.map((place)=><Pressable key={place.id} onPress={()=>focus(place)} style={[styles.card,{flexBasis:`${100/columns-1.6}%`}]}><PlaceMedia place={place}/><View style={styles.cardCopy}><Text numberOfLines={1} style={styles.cardTitle}>{place.name}</Text><Text numberOfLines={2} style={styles.cardSub}>{place.address||place.subtitle}</Text><View style={styles.meta}><Ionicons name="navigate-outline" size={12} color="#8992A4"/><Text style={styles.metaText}>{formatDistance(place.distanceMeters)||"Mapped place"}</Text></View><View style={styles.focus}><Ionicons name="map-outline" size={14} color="#7057D2"/><Text style={styles.focusText}>Show on map</Text></View></View></Pressable>)}</View>:null}
    {section==="packages"?<View style={styles.grid}>{TOUR_PACKAGE_PREVIEWS.filter((item)=>`${item.title} ${item.destination}`.toLowerCase().includes(query.toLowerCase())).map((item)=><View key={item.id} style={[styles.card,{flexBasis:`${100/columns-1.6}%`}]}><Image source={{uri:item.imageUrl}} contentFit="cover" style={styles.media}/><View style={styles.cardCopy}><Text style={styles.preview}>MARKETPLACE PREVIEW</Text><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardSub}>{item.destination} · {item.duration}</Text><Text style={styles.sample}>{item.samplePrice}</Text><View style={styles.focus}><Text style={styles.focusText}>Coming soon</Text></View></View></View>)}</View>:null}
    {section==="agencies"?<View style={styles.grid}>{TRAVEL_AGENCY_PREVIEWS.filter((item)=>`${item.name} ${item.specialties.join(" ")}`.toLowerCase().includes(query.toLowerCase())).map((item)=><View key={item.id} style={[styles.card,{flexBasis:`${100/columns-1.6}%`}]}><Image source={{uri:item.imageUrl}} contentFit="cover" style={styles.media}/><View style={styles.cardCopy}><Text style={styles.preview}>PROFILE PREVIEW</Text><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.cardSub}>{item.description}</Text><Text style={styles.metaText}>{item.specialties.join(" · ")}</Text><View style={styles.focus}><Text style={styles.focusText}>Marketplace preview</Text></View></View></View>)}</View>:null}
    {!loading&&!error&&section==="picks"&&!filtered.length?<View style={styles.state}><Ionicons name="search-outline" size={26} color="#8067DE"/><Text style={styles.stateTitle}>No matching places here.</Text><Text style={styles.stateText}>Try another category, search term, or wider radius.</Text></View>:null}
  </View></ScrollView></SafeAreaView>;
}
function PlaceMedia({place}:{place:DiscoverPlace}){const image=place.image?.verifiedEntityMatch?place.image.thumbnailUrl||place.image.url:null;return image?<Image source={{uri:image}} contentFit="cover" style={styles.media}/>:<LinearGradient colors={["#F0ECFF","#EDF5FF"]} style={[styles.media,styles.fallback]}><Ionicons name="location-outline" size={28} color="#8068DC"/><Text style={styles.noPhoto}>No verified place photo</Text></LinearGradient>;}
function normalizeCategory(value?:string):ExploreCategory{const decoded=value?decodeURIComponent(value):"All";return EXPLORE_CATEGORIES.find((item)=>item.name===decoded)?.name??"All";}
function finite(value:string|undefined,fallback:number){const n=Number(value);return Number.isFinite(n)?n:fallback;}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#FBFCFF"},content:{padding:18,paddingBottom:100},max:{width:"100%",maxWidth:1180,alignSelf:"center"},head:{flexDirection:"row",gap:11,alignItems:"flex-start"},back:{width:40,height:40,borderRadius:20,alignItems:"center",justifyContent:"center",backgroundColor:"#fff",borderWidth:1,borderColor:"#E5E8EE"},kicker:{color:"#8065E1",fontSize:7.5,fontWeight:"900",letterSpacing:.8},title:{marginTop:4,color:"#1C2540",fontSize:24,fontWeight:"900"},sub:{marginTop:3,color:"#8992A3",fontSize:8.5,fontWeight:"600"},search:{marginTop:15,minHeight:50,flexDirection:"row",alignItems:"center",gap:8,paddingHorizontal:13,borderRadius:17,backgroundColor:"#fff",borderWidth:1,borderColor:"#E6E8EE"},input:{flex:1,color:"#293149",fontSize:10.5,fontWeight:"600"},chips:{gap:7,paddingTop:11},chip:{minHeight:34,flexDirection:"row",alignItems:"center",gap:5,paddingHorizontal:11,borderRadius:17,backgroundColor:"#fff",borderWidth:1,borderColor:"#E4E7ED"},chipOn:{backgroundColor:"#937CE4",borderColor:"#937CE4"},chipText:{color:"#5E687B",fontSize:8,fontWeight:"900"},chipTextOn:{color:"#fff"},radii:{gap:6,paddingTop:8,paddingBottom:13},radius:{minHeight:29,paddingHorizontal:10,alignItems:"center",justifyContent:"center",borderRadius:13,backgroundColor:"#F4F4F7"},radiusOn:{backgroundColor:"#ECE7FF"},radiusText:{color:"#7C8596",fontSize:7.8,fontWeight:"800"},radiusTextOn:{color:"#6F57D2"},grid:{flexDirection:"row",flexWrap:"wrap",gap:12,alignItems:"stretch"},card:{minWidth:220,overflow:"hidden",borderRadius:20,backgroundColor:"#fff",borderWidth:1,borderColor:"#E5E8EE"},media:{height:155,backgroundColor:"#EEF1F5"},fallback:{alignItems:"center",justifyContent:"center"},noPhoto:{marginTop:6,color:"#89819C",fontSize:7.5,fontWeight:"800"},cardCopy:{padding:12},preview:{color:"#8065E1",fontSize:6.8,fontWeight:"900",letterSpacing:.7},cardTitle:{marginTop:3,color:"#283149",fontSize:10.8,fontWeight:"900"},cardSub:{marginTop:4,color:"#8992A4",fontSize:8,lineHeight:12,fontWeight:"600"},sample:{marginTop:6,color:"#3A445A",fontSize:9,fontWeight:"900"},meta:{marginTop:7,flexDirection:"row",alignItems:"center",gap:4},metaText:{color:"#828C9F",fontSize:7.8,fontWeight:"700"},focus:{marginTop:10,minHeight:34,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:5,borderRadius:13,backgroundColor:"#F3EFFF"},focusText:{color:"#7057D2",fontSize:8.2,fontWeight:"900"},state:{minHeight:220,alignItems:"center",justifyContent:"center",gap:7},stateTitle:{color:"#30394F",fontSize:11,fontWeight:"900"},stateText:{color:"#8992A4",fontSize:8.5,fontWeight:"600"},retry:{marginTop:4,minHeight:35,paddingHorizontal:13,alignItems:"center",justifyContent:"center",borderRadius:13,backgroundColor:"#F2EEFF"},retryText:{color:"#7057D2",fontSize:8.3,fontWeight:"900"}});
