import { createElement, useEffect, useMemo, useRef } from "react";
import { StyleSheet, View } from "react-native";
import type { DiscoverMapProps, DiscoverPlace } from "./DiscoverMap.types";

type Frame={contentWindow?:{postMessage(message:unknown,targetOrigin:string):void}|null};
export function DiscoverMap({places,selectedId,onSelect}:DiscoverMapProps){
  const frameRef=useRef<Frame|null>(null); const html=useMemo(()=>makeHtml(places,selectedId),[places,selectedId]);
  useEffect(()=>{const handler=(event:MessageEvent)=>{if(event.source!==frameRef.current?.contentWindow)return;const data=event.data as {type?:string;id?:string};if(data?.type==="trava-discover-select"&&data.id)onSelect(data.id);};window.addEventListener("message",handler);return()=>window.removeEventListener("message",handler);},[onSelect]);
  return <View style={styles.wrap}>{createElement("iframe",{ref:frameRef as never,title:"TRAVA Discover map",srcDoc:html,sandbox:"allow-scripts allow-same-origin",style:{width:"100%",height:"100%",border:0,display:"block",background:"#EAF5FF"}})}</View>;
}
function makeHtml(places:DiscoverPlace[],selectedId?:string|null){const data=JSON.stringify(places.map(p=>({...p,selected:p.id===selectedId}))).replace(/</g,"\\u003c");return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
*{box-sizing:border-box}html,body,#map{width:100%;height:100%;margin:0}body{overflow:hidden;background:#eaf5ff;font-family:-apple-system,BlinkMacSystemFont,'SF Pro Display','Segoe UI',sans-serif}.leaflet-container{background:#eaf5ff}.leaflet-tile{filter:saturate(.64) brightness(1.10) contrast(.84) hue-rotate(2deg);opacity:.92}.leaflet-control-zoom,.leaflet-control-attribution{display:none}
.pin{position:relative;width:62px;height:74px;display:flex;justify-content:center;filter:drop-shadow(0 10px 13px rgba(36,63,110,.20));cursor:pointer}.tail{position:absolute;top:48px;width:18px;height:18px;background:#fff;transform:rotate(45deg);border-radius:2px}.bubble{position:relative;z-index:2;width:58px;height:58px;border-radius:29px;padding:4px;background:#fff;box-shadow:0 0 0 1px rgba(214,224,237,.95)}.bubble img{width:100%;height:100%;object-fit:cover;border-radius:25px}.pin.sel .bubble{box-shadow:0 0 0 7px rgba(81,132,255,.14);transform:scale(1.04)}
.user{width:50px;height:50px;border-radius:25px;background:rgba(69,114,255,.14);display:flex;align-items:center;justify-content:center;box-shadow:0 0 0 12px rgba(74,119,255,.10)}.user:after{content:'';width:23px;height:23px;border-radius:50%;background:#3976ff;border:6px solid #fff;box-shadow:0 4px 13px rgba(31,88,225,.28)}
.locate{position:absolute;right:18px;bottom:18px;z-index:800;width:58px;height:58px;border:0;border-radius:29px;background:rgba(255,255,255,.97);box-shadow:0 9px 22px rgba(37,59,92,.15);color:#3b6cff;font-size:26px;cursor:pointer}.city{position:absolute;left:33%;top:63%;z-index:500;font-weight:900;font-size:25px;color:#17223d;text-shadow:0 1px 0 #fff}.river{position:absolute;right:5%;top:59%;z-index:500;color:#447edc;font-size:13px;transform:rotate(37deg)}
</style></head><body><div id="map"></div><div class="city">Riga</div><div class="river">Daugava River</div><button class="locate" id="locate">➤</button><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const pts=${data};const fallback=[56.9496,24.1052];const map=L.map('map',{zoomControl:false,attributionControl:false,scrollWheelZoom:true,doubleClickZoom:true,dragging:true,touchZoom:true,minZoom:2});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);const ll=[];pts.forEach(p=>{ll.push([p.latitude,p.longitude]);const html='<div class="pin '+(p.selected?'sel':'')+'"><div class="tail"></div><div class="bubble"><img src="'+esc(p.imageUrl)+'"></div></div>';const icon=L.divIcon({className:'',html,iconSize:[62,74],iconAnchor:[31,67]});const marker=L.marker([p.latitude,p.longitude],{icon,riseOnHover:true}).addTo(map);marker.on('click',()=>parent.postMessage({type:'trava-discover-select',id:p.id},'*'));});let current=fallback;const userIcon=L.divIcon({className:'',html:'<div class="user"></div>',iconSize:[50,50],iconAnchor:[25,25]});const userMarker=L.marker(current,{icon:userIcon,zIndexOffset:900}).addTo(map);
function fit(){if(ll.length>1){map.fitBounds(L.latLngBounds(ll).pad(.25),{maxZoom:13});}else if(ll.length===1){map.setView(ll[0],13);}else map.setView(fallback,13);}fit();if(navigator.geolocation){navigator.geolocation.getCurrentPosition(pos=>{current=[pos.coords.latitude,pos.coords.longitude];userMarker.setLatLng(current);if(!pts.length)map.setView(current,13);},()=>{}, {enableHighAccuracy:false,timeout:4500,maximumAge:300000});}document.getElementById('locate').onclick=()=>map.setView(current,14,{animate:true});setTimeout(()=>map.invalidateSize(),80);function esc(s){return String(s||'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}
</script></body></html>`;}
const styles=StyleSheet.create({wrap:{width:"100%",height:420,overflow:"hidden",borderRadius:28,borderWidth:1,borderColor:"#DDE5EF",backgroundColor:"#EAF5FF",boxShadow:"0 16px 34px rgba(35,58,91,.09)"}});
