-- TRAVA legacy migration compatibility marker.
-- The original historical migration was incompatible with the existing production schema.
-- It is intentionally superseded by 20260822182500_trip_workspace_compat_repair.sql.
-- Do not put destructive schema normalization in this historical file.
