import { Ionicons } from "@expo/vector-icons";
import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, LayoutAnimation, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { searchWorldPlaces, type WorldPlaceResult } from "@/features/maps/utils/world-place-search";
import type { AiPreferences } from "../types/ai.types";

const DAYS=["3–5 days","6–8 days","9–12 days","13+ days"];
const TRAVELERS=["1","2","3–4","5+"];
const STYLES=["Budget","Comfort","Luxury","Backpacker","Family","Adventure","Food-focused","Relaxed"];

export function AiPreferencePanel({preferences,expanded,onExpanded,onUpdate}:{preferences:AiPreferences;expanded:boolean;onExpanded(value:boolean):void;onUpdate<K extends keyof AiPreferences>(key:K,value:AiPreferences[K]):void}){
  const [query,setQuery]=useState(preferences.destination);const [suggestions,setSuggestions]=useState<WorldPlaceResult[]>([]);const [loading,setLoading]=useState(false);const request=useRef<AbortController|null>(null);
  useEffect(()=>setQuery(preferences.destination),[preferences.destination]);
  useEffect(()=>{request.current?.abort();if(!expanded||query.trim().length<2||query.trim()===preferences.destination.trim()){setSuggestions([]);setLoading(false);return;}const controller=new AbortController();request.current=controller;const timer=setTimeout(()=>{setLoading(true);void searchWorldPlaces(query,null,7,controller.signal).then(setSuggestions).catch(()=>{}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},220);return()=>{clearTimeout(timer);controller.abort();};},[expanded,query,preferences.destination]);
  const toggle=()=>{LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);onExpanded(!expanded);};
  const selectDestination=(item:WorldPlaceResult)=>{const value=[item.name,item.city,item.country].filter(Boolean).filter(unique).join(", ");onUpdate("destination",value);setQuery(value);setSuggestions([]);};
  return <View style={styles.panel}><Pressable onPress={toggle} style={styles.top}><View style={styles.topIcon}><Ionicons name="options-outline" size={18} color="#775EDD"/></View><View style={{flex:1}}><Text style={styles.kicker}>OPTIONAL CONTEXT</Text><Text style={styles.title}>Let’s start with your preferences</Text><Text numberOfLines={1} style={styles.summary}>{summary(preferences)}</Text></View><Ionicons name={expanded?"chevron-up":"chevron-down"} size={18} color="#7C8598"/></Pressable>
    {expanded?<View style={styles.body}><Text style={styles.label}>DESTINATION</Text><View style={styles.destination}><Ionicons name="search-outline" size={17} color="#858FA1"/><TextInput value={query} onChangeText={(value)=>{setQuery(value);onUpdate("destination",value);}} placeholder="Search any city or country…" placeholderTextColor="#9BA3B2" style={styles.input}/>{loading?<ActivityIndicator size="small" color="#8065E2"/>:query?<Pressable onPress={()=>{setQuery("");onUpdate("destination","");}}><Ionicons name="close-circle" size={17} color="#A4ABB8"/></Pressable>:null}</View>{suggestions.length?<View style={styles.suggestions}>{suggestions.map((item)=><Pressable key={item.id} onPress={()=>selectDestination(item)} style={styles.suggestion}><Ionicons name="location-outline" size={15} color="#8067DD"/><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={styles.suggestionName}>{item.name}</Text><Text numberOfLines={1} style={styles.suggestionSub}>{item.displayName}</Text></View></Pressable>)}</View>:null}
      <Choice label="TRIP DURATION" values={DAYS} selected={preferences.days} onSelect={(value)=>onUpdate("days",value)}/><Choice label="TRAVELERS" values={TRAVELERS} selected={preferences.travelers} onSelect={(value)=>onUpdate("travelers",value)}/><Choice label="TRAVEL STYLE" values={STYLES} selected={preferences.style} onSelect={(value)=>onUpdate("style",value)}/>
      <Pressable onPress={()=>{LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);onExpanded(false);}} style={styles.done}><Text style={styles.doneText}>Use these preferences as context</Text></Pressable><Text style={styles.note}>You can skip this panel and just type a travel question anytime.</Text>
    </View>:null}
  </View>;
}
function Choice({label,values,selected,onSelect}:{label:string;values:string[];selected:string;onSelect(value:string):void}){return <View style={styles.choice}><Text style={styles.label}>{label}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.track}>{values.map((value)=><Pressable key={value} onPress={()=>onSelect(selected===value?"":value)} style={[styles.chip,selected===value&&styles.chipOn]}><Text style={[styles.chipText,selected===value&&styles.chipTextOn]}>{value}</Text></Pressable>)}</ScrollView></View>}
function summary(value:AiPreferences){const selected=[value.destination,value.days,value.travelers?`${value.travelers} traveler${value.travelers==="1"?"":"s"}`:"",value.style].filter(Boolean);return selected.length?selected.join(" · "):"Add destination, duration, travelers, or style when useful.";}
function unique(value:unknown,index:number,values:unknown[]){return values.indexOf(value)===index;}
const styles=StyleSheet.create({panel:{overflow:"visible",borderRadius:22,backgroundColor:"rgba(255,255,255,.96)",borderWidth:1,borderColor:"#E8E4F1",boxShadow:"0 9px 24px rgba(48,54,74,.06)"},top:{minHeight:70,flexDirection:"row",alignItems:"center",gap:10,padding:12},topIcon:{width:40,height:40,borderRadius:15,alignItems:"center",justifyContent:"center",backgroundColor:"#F1ECFF"},kicker:{color:"#8065E1",fontSize:6.8,fontWeight:"900",letterSpacing:.8},title:{marginTop:2,color:"#273149",fontSize:11.5,fontWeight:"900"},summary:{marginTop:3,color:"#8A93A4",fontSize:7.8,fontWeight:"600"},body:{paddingHorizontal:12,paddingBottom:13,borderTopWidth:1,borderTopColor:"#F0EEF4"},label:{marginTop:12,marginBottom:6,color:"#8876C9",fontSize:7.2,fontWeight:"900",letterSpacing:.65},destination:{minHeight:45,flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:11,borderRadius:15,backgroundColor:"#F9F9FB",borderWidth:1,borderColor:"#E8E9ED"},input:{flex:1,color:"#303950",fontSize:9.5,fontWeight:"600"},suggestions:{marginTop:5,overflow:"hidden",borderRadius:15,borderWidth:1,borderColor:"#E9E9ED",backgroundColor:"#fff"},suggestion:{minHeight:48,flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:10,borderBottomWidth:1,borderBottomColor:"#F1F1F4"},suggestionName:{color:"#303950",fontSize:9.2,fontWeight:"900"},suggestionSub:{marginTop:2,color:"#8D95A5",fontSize:7.4,fontWeight:"600"},choice:{marginTop:2},track:{gap:6},chip:{minHeight:31,paddingHorizontal:10,alignItems:"center",justifyContent:"center",borderRadius:14,backgroundColor:"#F6F6F8",borderWidth:1,borderColor:"#E8E9ED"},chipOn:{backgroundColor:"#EEE9FF",borderColor:"#CFC4F7"},chipText:{color:"#697386",fontSize:7.8,fontWeight:"800"},chipTextOn:{color:"#684FCB"},done:{marginTop:14,minHeight:40,alignItems:"center",justifyContent:"center",borderRadius:14,backgroundColor:"#8064E3"},doneText:{color:"#fff",fontSize:8.7,fontWeight:"900"},note:{marginTop:6,color:"#969CAB",fontSize:7.2,lineHeight:10,textAlign:"center",fontWeight:"600"}});
